### ISSUE TITLE
Unable to install in Google colab.

### ISSUE THREAD

**Issue by vatsmartyradha** [Koukyosyumei/AIJack#114]
The installation fails most of the time. Please help.
Error:
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting aijack
  Downloading aijack-0.0.1a1.tar.gz (127 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.5/127.5 KB 1.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: aijack
  error: subprocess-exited-with-error
  
  × Building wheel for aijack (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for aijack (pyproject.toml) ... error
  ERROR: Failed building wheel for aijack
Failed to build aijack
ERROR: Could not build wheels for aijack, which is required to install pyproject.toml-based projects

**Comment by Koukyosyumei** [comment]
The default `pip` in google colab is not the latest version. I have confirmed that the below commands work:

```
!apt install -y libboost-all-dev
!pip install -U pip
!pip install "pybind11[global]"
!pip install aijack
```

**Comment by vatsmartyradha** [comment]
Thanks, I will check.
