### ISSUE TITLE
Typo on README.md

### ISSUE THREAD

**Issue by iamyifan** [Koukyosyumei/AIJack#119]
In the section `Supported Algorithms`, inside the first row of the table, `FedMD` should be changed to `FedKD`.

**Comment by Koukyosyumei** [comment]
Thank you for your report! Could you quickly submit a PR to fix it? Since AIJack supports both [FedMD](https://arxiv.org/abs/1910.03581) and [FedKD](https://arxiv.org/abs/2108.13323), the table should contain both.

**Comment by haroon26** [comment]
Hi @Koukyosyumei
I will be opening a PR on this issue.
