### ISSUE TITLE
Problem occurred when I run Reconstruct Single Data in Gradient-based Model Inversion Attack against Federated Learning

### ISSUE THREAD

**Issue by OctopusJIA** [Koukyosyumei/AIJack#159]
I followed the tutorial in the document to run the program,but all four methods in Reconstruct Single Data encounter the same error.

![reconstruction_single_sample_bug](https://github.com/Koukyosyumei/AIJack/assets/92537364/65380c9e-75c4-4f26-aa62-10509c77bc9e)

_RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward._

As described above, This error occurs after the local iteration is complete. Then I checked the code and found the following code in **GradientInversion_Attack** _line306_

`distance.backward(retain_graph=False)`

I don't know if **retain_gragph=False** is the core cause of this bug, but I really don't have a better solution right now.

**Comment by Koukyosyumei** [comment]
Thank you for your report. I fixed this bug.
