### ISSUE TITLE
We need help

### ISSUE THREAD

**Issue by Roua512** [Koukyosyumei/AIJack#34]
Hi, 
After executing this:
!pip install git+https://github.com/Koukyosyumei/AIJack

I faced this error:
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Can you help me?

**Comment by Koukyosyumei** [comment]
@Roua512 

One possible solution is installing pybind11. 

```
pip install pybind11
!pip install git+https://github.com/Koukyosyumei/AIJack
```

The above commands work at least in google colabo.

**Comment by Roua512** [comment]
Thank you so much.
It works.
