### ISSUE TITLE
Error#2 

### ISSUE THREAD

**Issue by Roua512** [Koukyosyumei/AIJack#35]
We are trying to execute the example_poison_attack.ipynb  code, and we faced this error:

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-4-ed5c608956f7>](https://localhost:8080/#) in <module>()
----> 1 X_train = np.load("data/X_train.npy", allow_pickle=True)
      2 y_train = np.load("data/y_train.npy", allow_pickle=True)
      3 X_valid = np.load("data/X_valid.npy", allow_pickle=True)
      4 y_valid = np.load("data/y_valid.npy", allow_pickle=True)

[/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py](https://localhost:8080/#) in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    415             own_fid = False
    416         else:
--> 417             fid = stack.enter_context(open(os_fspath(file), "rb"))
    418             own_fid = True
    419 

FileNotFoundError: [Errno 2] No such file or directory: 'data/X_train.npy'

**Comment by Koukyosyumei** [comment]
@Roua512 
Sorry for the late reply. I have updated the notebook. Could you check it works in your environment?

**Comment by Roua512** [comment]
yes it works, thank you.
