### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Roua512** [Koukyosyumei/AIJack#38]
Hi,

In the example_poison_attack code this line:
xc_attacked, log = attacker.attack(xc, 1, X_valid, y_valid_, num_iterations=200)

Can you please explain why we pass 1 instead of passing the actual value of yc?

**Comment by Koukyosyumei** [comment]
Sorry for the late response.  Since the example notebook trains a binary classifier ('3' vs '7'), the notebook replaces '3' with 1 and '7' with 0. Thus, we pass 1  to the attacker.

**Comment by Roua512** [comment]
Thank you so much.
Actually we are working on our graduation project, and we are trying to apply poisoning attack on CIFAR-10 dataset, but we are facing a problem now which is when displaying the image after attack it just shows a black image (before attack it goes will). Do have an idea what the problem could be? (could it be that the attack is only suitable for the mnist dataset?)

kindly, is there another way to contact you?

**Comment by Koukyosyumei** [comment]
One possible reason is that some of the pixel values are Nan, and you may be able to avoid this problem by decreasing the step size or the number of iterations. You can contact me with `takahashi-hideaki567@g.ecc.u-tokyo.ac.jp`.

**Comment by Roua512** [comment]
Thank you, we really appreciate your help ^_^.
