### ISSUE TITLE
The GS/GradInversion doesn't work

### ISSUE THREAD

**Issue by 410647675** [Koukyosyumei/AIJack#80]

**Comment by Koukyosyumei** [comment]
@410647675 

Thank you for your report. I'll check this issue. Could you share the version of Python, Pytorch, and Numpy?

**Comment by 410647675** [comment]
Hi thank you for your answer, I tried:
1.  Python == 3.9.0, Pytorch == 1.12.1, and Numpy == 1.23.3
2. Python == 3.7.13, Pytorch == 1.12.1, Numpy == 1.21.6
The errors are the same for GradInversion/CPL/GS

If I could ask, would you please paste your env list?

**Comment by 410647675** [comment]
Sorry, I found this is actually my fault, please close it.
